// Code generated by generate.go. DO NOT EDIT.

package intermediates

const (
	expectedCountPublicAllIntermediateCerts           = 2546
	expectedCountPublicAllIntermediateCertsHashes     = 2546
	expectedCountMozillaIntermediateCertsReport       = 1874
	expectedCountMozillaIntermediateCertsReportHashes = 1874
	expectedCountPublicIntermediateCertsRevoked       = 2733
	expectedCountPublicIntermediateCertsRevokedHashes = 2755
)
