// Code generated by generate.go. DO NOT EDIT.

package intermediates

const (
	expectedCountPublicAllIntermediateCerts           = 2567
	expectedCountPublicAllIntermediateCertsHashes     = 2567
	expectedCountMozillaIntermediateCertsReport       = 1779
	expectedCountMozillaIntermediateCertsReportHashes = 1779
	expectedCountPublicIntermediateCertsRevoked       = 2914
	expectedCountPublicIntermediateCertsRevokedHashes = 2936
)
