// Code generated by generate.go. DO NOT EDIT.

package intermediates

const (
	expectedCountPublicAllIntermediateCerts           = 2501
	expectedCountPublicAllIntermediateCertsHashes     = 2501
	expectedCountMozillaIntermediateCertsReport       = 1840
	expectedCountMozillaIntermediateCertsReportHashes = 1840
	expectedCountPublicIntermediateCertsRevoked       = 2635
	expectedCountPublicIntermediateCertsRevokedHashes = 2657
)
