name: Update intermediates collection
on:
  # NOTE: Omit automatic tagging for pushes.
  # push:

  # Permit manually triggering workflow for testing.
  workflow_call:

  # This is the primary means of triggering this workflow.
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *
    - cron: '4 2 * * *' # daily at 2:04

permissions:
  contents: write

jobs:
  update:
    name: Download, test, and commit changes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: "ghcr.io/atc0005/go-ci:go-ci-oldstable"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: Regenerate pool
        run: go generate

      - name: Run tests
        run: go test -race ./...

      # - name: Record semantic version using git-describe-semver
      #   uses: docker://ghcr.io/choffmeister/git-describe-semver:0.3.11
      #   id: git-describe-semver
      #   with:
      #     args: >-
      #       --fallback="v0.0.0"
      #       --drop-prefix=false
      #       --prerelease-prefix="dev"
      #       --prerelease-suffix=""
      #       --prerelease-timestamped="false"
      #       --format="version=<version>"
      #       $GITHUB_OUTPUT

      - name: Record semantic version using git-describe-semver
        uses: docker://ghcr.io/choffmeister/git-describe-semver:0.4.0
        id: git-describe-semver
        with:
          args: >-
            --next-release patch
            --format="version=<version>"
            $GITHUB_OUTPUT

      - name: Print semantic version generated by git-describe-semver
        run: |
          echo "${{ steps.git-describe-semver.outputs.version }}"

      - name: Configure Git author settings
        run: |-
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Print Git author settings
        run: |-
          git config --get user.name
          git config --get user.email

      - name: Commit and push if changed
        run: |-
          git commit -a -m "intermediates: update certificates" || exit 0

          bash create-tag.sh "${{ steps.git-describe-semver.outputs.version }}"

          git push
          git push --tags
